title: OpenCurve Documentation
description: Documentation for OpenCurve - The platform for utility-driven tokens with native AI agents
baseurl: "/opencurve-docs" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Theme settings
remote_theme: pmarsceill/just-the-docs
color_scheme: dark
search_enabled: true
heading_anchors: true

# Aux links for the upper right navigation
aux_links:
  "OpenCurve Website":
    - "https://opencurve.fun"
  "GitHub":
    - "https://github.com/username/opencurve-docs"

# Footer content
# appears at the bottom of every page's main content
footer_content: "Copyright &copy; 2023-2025 OpenCurve. All rights reserved."

# Back to top link
back_to_top: true
back_to_top_text: "Back to top"

# Footer last edited timestamp
last_edit_timestamp: true # show or hide edit time - page must have `last_modified_date` defined in the frontmatter
last_edit_time_format: "%b %e %Y at %I:%M %p" # uses ruby's time format: https://ruby-doc.org/stdlib-2.7.0/libdoc/time/rdoc/Time.html
